signal_generator:
  ros__parameters:
    signal_type: 0
    default:
      amplitude : 0.5
      frequency: 2.0
      offset: 0.0
      phase: 0.0
      time: 0.0
    square:
      amplitude : 2.0
      frequency: 5.0
      offset: -1.0
      phase: 0.0
      time: 0.0
    sawtooth:
      amplitude : 1.0
      frequency: 10.0
      offset: 2.5
      phase: 0.7853
      time: 0.0
    cosine:
      amplitude : 0.5
      frequency: 2.0
      offset: 0.0
      phase: 0.0
      time: 0.0
    tangent:
      amplitude : 0.5
      frequency: 2.0
      offset: 0.0
      phase: 0.0
      time: 0.0

